{
 "title": "Virtual Machine+Power Consumption",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "one_vm_id", "label": "Virtual Machine ID", "query": { "query": "label_values(one_vm_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_libvirt_net_devices{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_net_rx_drops{one_vm_id=\"$one_vm_id\"}) + sum(opennebula_libvirt_net_tx_drops{one_vm_id=\"$one_vm_id\"}) + sum(opennebula_libvirt_net_rx_errors{one_vm_id=\"$one_vm_id\"}) + sum(opennebula_libvirt_net_tx_errors{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_net_rx_packets{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_net_tx_packets{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Statics (Bytes RX/TX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opennebula_libvirt_net_rx_total_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_net_rx_total_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_libvirt_block_devices{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_block_virtual_bytes{one_vm_id=\"$one_vm_id\"}) + sum(opennebula_libvirt_net_tx_drops{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_block_physical_bytes{one_vm_id=\"$one_vm_id\"}) + sum(opennebula_libvirt_net_tx_errors{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Device Statics (Bytes RD/WR)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opennebula_libvirt_block_rd_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_block_wr_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_libvirt_vcpu_maximum{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_vm_cpu_ratio{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "opennebula_libvirt_cpu_seconds_total{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_cpu_user_seconds_total{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_cpu_system_seconds_total{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domain vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(opennebula_libvirt_vcpu_time_seconds_total{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_libvirt_vcpu_wait_seconds_total{one_vm_id=\"$one_vm_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_libvirt_memory_total_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_memory_maximum_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_memory_rss_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_libvirt_memory_available_bytes{one_vm_id=\"$one_vm_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power consumption of the VM",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "opennebula_vm_power_consumption_uW{one_vm_id=\"$one_vm_id\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}